# Generated by Django 5.2 on 2025-04-28 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('router', 'Router'), ('mikrotik', 'Mikrotik'), ('switch', 'Switch'), ('radio', 'Radio')], max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100, unique=True)),
                ('imei', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('operador', models.CharField(choices=[('tigo', 'Tigo'), ('claro', 'Claro'), ('movistar', 'Movistar'), ('no', 'No')], max_length=100)),
                ('numero_sincard', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('SIN_ASIGNAR', 'SIN_ASIGNAR'), ('ASIGNADO', 'ASIGNADO')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PuntoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_punto', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('modalidad', models.CharField(choices=[('local', 'Local'), ('compumovil', 'Compumovil')], max_length=25)),
                ('rango_valor', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('tecnico', 'Técnico'), ('comunicaciones', 'Comunicaciones')], max_length=50)),
                ('password_usuario', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_zona', models.PositiveIntegerField(unique=True)),
                ('nombre_admin_zona', models.CharField(max_length=255)),
                ('apellido_admin_zona', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('orientacion', models.CharField(choices=[('ciudad', 'Ciudad'), ('poblaciones', 'Poblaciones')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_falla', models.CharField(choices=[('cable partido', 'Cable partido'), ('perdida de conexion', 'Pérdida de conexión'), ('antena caida', 'Antena caída'), ('instalacion de antena', 'Instalación de antena'), ('reubicacion de caja', 'Reubicación de caja'), ('desmonte dispositivos', 'Desmonte dispositivos'), ('inventario', 'Inventario')], max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_asignacion', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado')], default='pendiente', max_length=20)),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_ti.puntoventa')),
                ('tecnico', models.ForeignKey(limit_choices_to=models.Q(('rol', 'tecnico'), ('rol', 'comunicaciones'), ('rol', 'administrador'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='servicios_ti.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_falla', models.TextField()),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('asignacion_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_ti.asignacionservicio')),
                ('tecnico_resolucion', models.ForeignKey(limit_choices_to=models.Q(('rol', 'tecnico'), ('rol', 'comunicaciones'), ('rol', 'administrador'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='servicios_ti.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DispositivoPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_instalacion', models.DateField()),
                ('estado', models.CharField(choices=[('SIN_ASIGNAR', 'SIN_ASIGNAR'), ('ASIGNADO', 'ASIGNADO')], max_length=100)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_ti.dispositivo')),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_ti.puntoventa')),
                ('nombre_responsable', models.ForeignKey(limit_choices_to=models.Q(('rol', 'tecnico'), ('rol', 'comunicaciones'), ('rol', 'administrador'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='servicios_ti.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=10)),
                ('fila_id', models.IntegerField(blank=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('datos_antiguos', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('usuario_app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_ti.zona'),
        ),
    ]
