# Generated by Django 5.2 on 2025-04-29 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios_ti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecolectoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dispositivo', models.CharField(blank=True, choices=[('router', 'Router'), ('mikrotik', 'Mikrotik'), ('switch', 'Switch'), ('radio', 'Radio'), ('otro', 'Otro')], max_length=50, null=True)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('imei', models.CharField(blank=True, max_length=15, null=True)),
                ('numerosimcard', models.CharField(blank=True, max_length=15, null=True)),
                ('operador', models.CharField(blank=True, choices=[('tigo', 'Tigo'), ('claro', 'Claro'), ('movistar', 'Movistar'), ('no', 'No')], max_length=20, null=True)),
                ('fecha_recoleccion', models.DateField(auto_now_add=True)),
                ('empleadotic', models.ForeignKey(limit_choices_to=models.Q(('rol', 'tecnico'), ('rol', 'comunicaciones'), ('rol', 'administrador'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='servicios_ti.usuario', verbose_name='Empleado TIC')),
                ('punto_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios_ti.puntoventa')),
            ],
        ),
    ]
